site_name: Task 1
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tans.link
    - content.code.annotation
    - content.code.copy
    - navigation.top
    - toc.integrate
    - navigation.tabs
    - navigation.sections
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tenzinkunga911/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - footnotes
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list